### ISSUE TITLE
Regression in 2.7.6: HTTPSConnection doesn't work! (AttributeError: 'module' object has no attribute '_create_default_https_context')

### ISSUE THREAD

**Issue by petsuter** [IronLanguages/main#1354]
This worked in 2.7.5:

```
IronPython 2.7.5 (2.7.5.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import httplib
>>> httplib.HTTPSConnection('example.com')
<httplib.HTTPSConnection instance at 0x000000000000002C>
```

But is broken in 2.7.6.3:

```
IronPython 2.7.6.3 (2.7.6.3) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import httplib
>>> httplib.HTTPSConnection('example.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\httplib.py", line 1261, in __init__
AttributeError: 'module' object has no attribute '_create_default_https_context'
```

Looks like the `httplib` module was upgraded (in changeset 80282b39ca5d93e733745b64bae2a67c73e228c9?) but the `ssl` module still does not know about `SSLContext`.

**Comment by slide** [comment]
This is most likely because of an upgrade to the Python stdlib.

**Comment by slide** [comment]
I'm working on this, will hopefully have a fix soon.

**Comment by tomunger** [comment]
I just ran into this bug with IronPython 2.7.6.3 on Windows.  
What is my best option?  Is there a way to get unreleased 2.7.6.4?  Or maybe a std library that works with 2.7.6.3?
Revert to 2.7.5?
Thanks,
Tom

**Comment by slide** [comment]
I would try 2.7.7, see https://github.com/IronLanguages/main/releases/tag/ipy-2.7.7

**Comment by tomunger** [comment]
Thanks, that worked.  
And I learned how to navigate to releases on GitHub.

**Comment by slide** [comment]
Glad it's working for you!
